import { auth } from "@/auth";
import { Footer, Header, OverlayScrollbar } from "@/components/organisms";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  authenticated,
    public: publicPages,
}: Readonly<{
  authenticated: React.ReactNode;
    public: React.ReactNode;
}>) {
  const session = await auth();
  
  return (
    <ViewTransitions>
    <html lang="en" data-overlayscrollbars-initialize>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {session ? authenticated : publicPages}
        <Footer />
        <OverlayScrollbar />
      </body>
    </html>
    </ViewTransitions>
  );
}
